package backend.cardapio.entidades;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Cardapio")
public class Cardapio {

    private String item;
    private String nome;
    private String descricao;
    private String codigo;
    private Date valor;

    public Cardapio() {
    }

    public Cardapio(String item, String nome, String descricao, Date valor) {
        this.item = item;
        this.nome = nome;
        this.descricao = descricao;
        this.valor = valor;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getCodigo() {
        return codigo;
    }
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @DynamoDBAttribute
    public String getNome() {
        return nome;
    }
    public void setNome(String nome) {
        this.nome = nome;
    }

    @DynamoDBAttribute
    public String getDescricao() {
        return descricao;
    }
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @DynamoDBAttribute
    public Date getValor() {
        return valor;
    }
    public void setValor(Date valor) {
        this.valor = valor;
    }

    @DynamoDBAttribute
    public String getItem() {
        return this.item;
    }
    public void setItem(String item) {
        this.item = item;
    }

    @Override
    public String toString() {
        return "Cardapio [codigo=" + codigo + ", nome=" + nome + ", descricao=" + descricao + 
               ", valor=" + valor + ", item=" + item + "]";
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((item == null) ? 0 : item.hashCode());
        result = prime * result + ((nome == null) ? 0 : nome.hashCode());
        result = prime * result + ((descricao == null) ? 0 : descricao.hashCode());
        result = prime * result + ((valor == null) ? 0 : valor.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;

        Cardapio other = (Cardapio) obj;

        if (item == null) {
            if (other.item != null) return false;
        } else if (!item.equals(other.item)) return false;

        if (nome == null) {
            if (other.nome != null) return false;
        } else if (!nome.equals(other.nome)) return false;

        if (descricao == null) {
            if (other.descricao != null) return false;
        } else if (!descricao.equals(other.descricao)) return false;

        if (valor == null) {
            if (other.valor != null) return false;
        } else if (!valor.equals(other.valor)) return false;

        return true;
    }
}
